import predict
from helpers import *
from timeit import default_timer as timer
import soundfile as sf

def dictionaryToCSVLine(dictionary, algorithm, b, isCustomFFT, numDownsamples, octaveTrick, predFreq, time):
    d = dictionary.copy()
    d["algorithm"] = algorithm

    d["b"] = b
    d["isCustomFFT"] = isCustomFFT
    d["numDownsamples"] = numDownsamples
    d["octaveTrick"] = octaveTrick

    d["predFreq"] = predFreq
    d["time"] = time

    d["percentErr"] = getPercentageError(d["trueFreq"], predFreq)
    d["absMidiErr"] = getAbsoluteMIDIError(d["trueFreq"], predFreq)
    d["correctNote"] = isWithin100Cents(d["trueFreq"], predFreq)
    d["correctNoteWithOctaveErr"] = isWithin100CentsWithOctaveError(d["trueFreq"], predFreq)

    x = ""
    for val in d:
        x += str(d[val]) + ","
    return x[:-1] + "\n"

def testToCSV(signal, testInfo, csvFilePath):
    '''This function assumes that the csv file already contains headers: 
        signalType, algorithm, b, isCustomFFT, numDownsamples, octaveTrick, sampleRate, expectedMin, expectedMax, instrument, noise, extraGain, windowFunction, trueFreq, predFreq, time, percentErr, absMidiErr, correctNote, correctNoteWithOctaveErr
    ALSO assumes that *testInfo* is a dictionary with these headers as it's keys and the values being the corresponding values.
        In the case of the hyperparameter keys (b, isCustomFFT, numDownsamples, octaveTrick), the corresponding values should be a collection of all the possible values that need evaluating.
    The function then writes in the relevant data generated by predicting the pitch of 'signal' using all prediction algorithms.'''
    
    with open(csvFilePath, "a") as f:
        ##  execute predictions in the following order: 
        ##      zerocross, autocorrelation, AMDF, naiveFT, naiveFTWithPhase, cepstrum, HPS, trimmedMean (with trimSize=2/7), median

        sampleRate = testInfo["sampleRate"]
        expectedMin = testInfo["expectedMin"]
        expectedMax = testInfo["expectedMax"]

        # The following lists are already filled in to allow for indexing while we iterate through all desired hyperparameter values
        #   Since b is the only hyperparameter affecting just one algorithm its results are saved in a sub-list so that the mean & median predictions may be
        #   calculated more easily for each possible hyperparameter combination
        executionTimes = [0,0,[],0,0,0,0]
        predictions = [0,0,[],0,0,0,0]

        ## Calculations
        #zerocross
        start = timer()
        pred = predict.zerocross(signal, sampleRate)
        end = timer()

        predictions[0] = pred
        executionTimes[0] = end-start

        f.write(dictionaryToCSVLine(testInfo,"zerocross","n/a","n/a","n/a","n/a", pred, end-start))

        #autocorrelation
        start = timer()
        pred = predict.autocorrelation(signal, sampleRate, expectedMin, expectedMax)
        end = timer()

        predictions[1] = pred
        executionTimes[1] = end-start

        f.write(dictionaryToCSVLine(testInfo,"autocorrelation","n/a","n/a","n/a","n/a", pred, end-start))

        #AMDF
        for b in testInfo["b"]:
            start = timer()
            pred = predict.AMDF(signal, sampleRate, b, expectedMin, expectedMax)
            end = timer()

            predictions[2].append(pred)
            executionTimes[2].append(end-start)

            f.write(dictionaryToCSVLine(testInfo,"AMDF",b,"n/a","n/a","n/a", pred, end-start))

        for isCustomFFT in testInfo["isCustomFFT"]:
            #naiveFT
            naiveFTPredictions = []
            start = timer()
            pred = predict.naiveFT(signal, sampleRate, isCustomFFT, expectedMin, expectedMax)
            end = timer()

            predictions[3] = pred
            executionTimes[3] = end-start

            f.write(dictionaryToCSVLine(testInfo,"naiveFT","n/a",isCustomFFT,"n/a","n/a", pred, end-start))

            #naiveFTWithPhase
            naiveFTWithPhasePredictions = []
            start = timer()
            pred = predict.naiveFTWithPhase(signal, sampleRate, isCustomFFT, expectedMin, expectedMax)
            end = timer()

            predictions[4] = pred
            executionTimes[4] = end-start

            f.write(dictionaryToCSVLine(testInfo,"naiveFTWithPhase","n/a",isCustomFFT,"n/a","n/a", pred, end-start))

            #cepstrum
            cepstrumPredictions = []
            start = timer()
            pred = predict.cepstrum(signal, sampleRate, isCustomFFT, expectedMin, expectedMax)
            end = timer()

            predictions[5] = pred
            executionTimes[5] = end-start

            f.write(dictionaryToCSVLine(testInfo,"cepstrum","n/a",isCustomFFT,"n/a","n/a", pred, end-start))

            for numDownsamples in testInfo["numDownsamples"]:
                for octaveTrick in testInfo["octaveTrick"]:
                    #HPS
                    start = timer()
                    pred = predict.HPS(signal, sampleRate, isCustomFFT, numDownsamples, expectedMin, expectedMax, octaveTrick)
                    end = timer()

                    predictions[6] = pred
                    executionTimes[0] = end-start

                    f.write(dictionaryToCSVLine(testInfo,"HPS","n/a",isCustomFFT,numDownsamples,octaveTrick, pred, end-start))

                    for bIndex in range(len(testInfo["b"])):
                        #trimmedMean - excluding smallest two and largest two predictions and max
                        pred = getTrimmedMean(predictions[:2] + [predictions[2][bIndex]] + predictions[3:], 2/7)
                        time = sum(executionTimes[:2] + [executionTimes[2][bIndex]] + executionTimes[3:])

                        f.write(dictionaryToCSVLine(testInfo,"trimmedMean",testInfo["b"][bIndex],isCustomFFT,numDownsamples,octaveTrick, pred, time))

                        #median
                        pred = getMedian(predictions[:2] + [predictions[2][bIndex]] + predictions[3:])

                        f.write(dictionaryToCSVLine(testInfo,"median",testInfo["b"][bIndex],isCustomFFT,numDownsamples,octaveTrick, pred, time))

def getPitchDataMeanErrors(expectedPitchData, actualPitchData):
    '''Assumes both arguments are lists of frequency predictions with the same time spacing between data points.
    Returns a list of the form 
        [meanPercentError, meanAbsoluteMidiError, meanCorrectNote, meanCorrectNoteWithOctaveError]
    with each of those values defined as in helpers.py and analyse.py.'''
    numDataPoints = min(len(expectedPitchData), len(actualPitchData))
    meanErrors = [0,0,0,0]

    for i in range(numDataPoints):
        meanErrors[0] += getPercentageError(expectedPitchData[i], actualPitchData[i])
        meanErrors[1] += getAbsoluteMIDIError(expectedPitchData[i], actualPitchData[i])
        meanErrors[2] += isWithin100Cents(expectedPitchData[i], actualPitchData[i])
        meanErrors[3] += isWithin100CentsWithOctaveError(expectedPitchData[i], actualPitchData[i])

    return [x/numDataPoints for x in meanErrors]

def ratioTestToCSV(signal, signalLocation, testInfo, csvFilePath):
    '''This function assumes that the csv file already contains headers: 
        signalType, expectedMin, expectedMax, instrument, ratio, time, meanPercentErr, meanAbsMidiErr, meanCorrectNote, meanCorrectNoteWithOctaveErr
    ALSO assumes that *testInfo* is a dictionary with these headers as it's keys and the values being the corresponding values.'''
    originalPitchProfile = PitchProfile(signalLocation, testInfo["sampleRate"], "naiveFTWithPhase", {"isCustomFFT" : False}, testInfo["instrument"], blockSize=2048, overlap=1024, customName=testInfo["signalType"])
    originalPitchProfile.writeLog(signalLocation[:-4] + ".log")

    start = timer()
    shiftedSignal = phaseVocoderPitchShift(signal, testInfo["sampleRate"], testInfo["scalingFactor"], windowLength=512, overlapLength=384, getHanningWindow(512))
    end = timer()

    sf.write(signalLocation[:-4] + "SHIFTED.wav", shiftedSignal)

    shiftedPitchProfile = PitchProfile(signalLocation[:-4] + "SHIFTED.wav", testInfo["sampleRate"], "naiveFTWithPhase", {"isCustomFFT" : False}, testInfo["instrument"], blockSize=2048, overlap=1024, customName=testInfo["signalType"]+"SHIFTED")
    shiftedPitchProfile.writeLog(signalLocation[:-4] + "SHIFTED.log")

    expectedPitchData = [x*float(testInfor["scalingFactor"]) for x in originalPitchProfile.pitchData]

    pitchDataMeanErrors = getPitchDataMeanErrors(expectedPitchData, shiftedPitchProfile.pitchData)

    with open(csvFilePath, "a") as f:
        f.write("%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s\n" % (testInfo["signalType"], testInfo["sampleRate"], testInfo["expectedMin"], testInfo["expectedMax"], testInfo["instrument"], testInfo["sclaingFactor"], end-start, pitchDataMeanErrors[0], pitchDataMeanErrors[1], pitchDataMeanErrors[2], pitchDataMeanErrors[3]))


def correctingTestToCSV(signal, signalLocation, testInfo, csvFilePath):
    '''This function assumes that the csv file already contains headers: 
        signalType, expectedMin, expectedMax, instrument, correctingTo, time, meanPercentErr, meanAbsMidiErr, meanCorrectNote, meanCorrectNoteWithOctaveErr
    ALSO assumes that *testInfo* is a dictionary with these headers as it's keys and the values being the corresponding values.'''
    originalPitchProfile = PitchProfile(signalLocation, testInfo["sampleRate"], "naiveFTWithPhase", {"isCustomFFT" : False}, testInfo["instrument"], blockSize=2048, overlap=1024, customName=testInfo["signalType"])
    originalPitchProfile.writeLog(signalLocation[:-4] + ".log")

    start = timer()
    correctedSignal = correctPitch(originalPitchProfile)
    end = timer()

    sf.write(signalLocation[:-4] + "CORRECTED.wav", correctedSignal)

    shiftedPitchProfile = PitchProfile(signalLocation[:-4] + "CORRECTED.wav", testInfo["sampleRate"], "naiveFTWithPhase", {"isCustomFFT" : False}, testInfo["instrument"], blockSize=2048, overlap=1024, customName=testInfo["signalType"]+"CORRECTED")
    shiftedPitchProfile.writeLog(signalLocation[:-4] + "CORRECTED.log")

    expectedPitchData = [noteNameToFreq(getNoteName(x)) for x in originalPitchProfile.pitchData]

    pitchDataMeanErrors = getPitchDataMeanErrors(expectedPitchData, shiftedPitchProfile.pitchData)

    with open(csvFilePath, "a") as f:
        f.write("%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s\n" % (testInfo["signalType"], testInfo["sampleRate"], testInfo["expectedMin"], testInfo["expectedMax"], testInfo["instrument"], testInfo["correctingTo"], end-start, pitchDataMeanErrors[0], pitchDataMeanErrors[1], pitchDataMeanErrors[2], pitchDataMeanErrors[3]))
        

def matchingTestToCSV(signal, matchingSignal, testInfo, csvFilePath):
    '''This function assumes that the csv file already contains headers: 
        signalType, expectedMin, expectedMax, instrument, matchingSignalType, matchingExpectedMin, matchingExpectedMax, matchingIntrument, time, meanPercentErr, meanAbsMidiErr, meanCorrectNote, meanCorrectNoteWithOctaveErr
    ALSO assumes that *testInfo* is a dictionary with these headers as it's keys and the values being the corresponding values.'''
    originalPitchProfile = PitchProfile(signalLocation, testInfo["sampleRate"], "naiveFTWithPhase", {"isCustomFFT" : False}, testInfo["instrument"], blockSize=2048, overlap=1024, customName=testInfo["signalType"])
    originalPitchProfile.writeLog(signalLocation[:-4] + ".log")

    start = timer()
    correctedSignal = correctPitch(originalPitchProfile)
    end = timer()

    sf.write(signalLocation[:-4] + "CORRECTED.wav", correctedSignal)

    shiftedPitchProfile = PitchProfile(signalLocation[:-4] + "CORRECTED.wav", testInfo["sampleRate"], "naiveFTWithPhase", {"isCustomFFT" : False}, testInfo["instrument"], blockSize=2048, overlap=1024, customName=testInfo["signalType"]+"CORRECTED")
    shiftedPitchProfile.writeLog(signalLocation[:-4] + "CORRECTED.log")

    expectedPitchData = [noteNameToFreq(getNoteName(x)) for x in originalPitchProfile.pitchData]

    pitchDataMeanErrors = getPitchDataMeanErrors(expectedPitchData, shiftedPitchProfile.pitchData)

    with open(csvFilePath, "a") as f:
        f.write("%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s\n" % (testInfo["signalType"], testInfo["sampleRate"], testInfo["expectedMin"], testInfo["expectedMax"], testInfo["instrument"], testInfo["correctingTo"], end-start, pitchDataMeanErrors[0], pitchDataMeanErrors[1], pitchDataMeanErrors[2], pitchDataMeanErrors[3]))
  